language: rust
cache: cargo

matrix:
  include:
    # OS compat
    - os: linux
    - os: osx

    # rustc version compat
    - rust: 1.22.0 # oldest supported version, keep in sync with README.md
    - rust: beta
    - rust: nightly

    # deployments
    - env: DEPLOY=1 TARGET=x86_64-apple-darwin
      script: cargo build --release --target $TARGET --features=all
      os: osx
    - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl OPENSSL_DIR=$HOME/openssl-musl
      before_script: ./scripts/travis-musl-openssl.sh
      script: cargo build --release --target $TARGET --features=all
      addons:
        apt:
          packages:
          - musl-tools
  allow_failures:
    - rust: nightly

before_script:
  - if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then export EXTRA_FEATURES=unstable; fi

script:
  - cargo build --verbose --features="all ${EXTRA_FEATURES}"
  - RUST_BACKTRACE=1 cargo test --all --verbose --features="all ${EXTRA_FEATURES}"

before_deploy:
  - name="sccache-$TRAVIS_TAG-$TARGET"
  - mkdir $name
  - cp target/$TARGET/release/sccache $name/
  - cp README.md LICENSE $name/
  - tar czvf $name.tar.gz $name

deploy:
  api_key:
    secure: "MCgmbyfermdkVSs1NrKV38w7ocma4aHU/tjYMjszZYH1ZvUkqbHk4fUZkBH3Nu01r8Pbci7NF3SKLRvt0BG3J7lo1mpinc72wTSc+uQg6dJnNiCUYqH3vLqqy1KFop+U3j41iZlZ1/nQ/wZWIXxxuD+XJ/z1M1T45b8mL+ITrGV01/XF+cB+gSyjGMwDdFlXMu0aL4kSMXFiiLpH63FScAzReObSg6iRuq5vSEHl9xCWG91C5RZrW9dIlXHW21Pwsu+CT7hO1CcdmV48vxwAD2A9YdrOXFBlbMxLlspB/SZzjkuuAlpJf8QvWmnvXUceUklmZsOoVOk0dsv1hkzaFgp3vcM/rq9xAVk5eug+jWirP+YPXphI03jXANRHvw36B32xqPpKGHBAZy/B2dyaX/pD44aGBDxA/NBDBL4aGd2UY8nXilz1bljgHhgCSkVCX9eNQx5KKigJePO8tCkVqPSWLsUzI5XBIs6SjmPEjldWWLECkY9vhfk5DA+CabxO0/c5aL5Rfx6EbMSKbmB77qaddkogGK7igHLmk8DJD9uc+5BSURUeXb0+uvYovZMX7Bz4vS4yzhmPU23ldfc+Zddn/PpDATGFg7M/yyKtN3v/HeEXIXcG2aJLP5jMEo/7BSSZg01drvwb3a/4EvKTO0wkdfyIc5Z/le8g/8iXL6o="
  file_glob: true
  file: sccache-$TRAVIS_TAG-$TARGET.tar.gz
  on:
    condition: $DEPLOY = 1
    tags: true
  provider: releases
  skip_cleanup: true
